import React from 'react';
import { MainLayout } from '../components/MainLayout';
import { ContentSection } from '../components/ContentSection';

const ChallengesAndConcernsPage: React.FC = () => {
  const breadcrumbItems = [
    { label: 'Challenges and Concerns', path: '/challenges' }
  ];

  return (
    <MainLayout
      breadcrumbItems={breadcrumbItems}
      currentPath="/challenges"
      title="Challenges and Concerns when Using AI in Education"
    >
      <ContentSection title="Key Challenges">
        <div className="prose prose-amber max-w-none">
          <p className="mb-4">
            Colleges and universities must deal with the ethical and practical issues raised by the usage of AI tools. 

          </p>
          <p className="mb-4">
          Students are increasingly turning in work generated by AI, making it harder to tell the difference between original and plagiarized work. Although there have been many approaches that show promise in identifying AI-generated text, detection is made more difficult by ChatGPT’s human-like speaking style [1]. Over-reliance on AI can affect individuals’ critical thinking abilities and writing skills. 
          </p>
          <p className="mb-4">
          Secondly, premium versions of AI, such as ChatGPT Plus, may provide students unfair advantages, making inequality worse [2]. Privacy concerns also discourage adoption among some groups, especially those who are unwilling to share their data. These issues raise questions about equity and access disparities. 
          </p>
          <p className="mb-4">
          The advent of AI could also make traditional assignments obsolete, highlighting the role of in-person exams, oral defenses, or process-based evaluation. Therefore, institutions need to find a balance between the benefits of AI and restrictions like transparency guidelines and honor standards. 
          </p>
          
          <div className="bg-amber-50 p-6 rounded-lg">
            <h3 className="text-lg font-semibold text-amber-900 mb-4">References</h3>
            <ol className="list-decimal list-inside space-y-2 text-sm text-amber-800">
              <li>
              Cotton, D. R. E., Cotton, P. A., & Shipway, J. R. (2023). Chatting and cheating: Ensuring academic integrity in the era of ChatGPT. Innovations in Education and Teaching International. https://doi.org/10.1080/14703297.2023.2190148
              </li>
              <li>
              Jo, H. (2024). From concerns to benefits: A comprehensive study of ChatGPT usage in education. International Journal of Educational Technology in Higher Education, 21(1), 35. https://doi.org/10.1186/s41239-024-00471-4

              </li>
            </ol>
          </div>
        </div>
      </ContentSection>
    </MainLayout>
  );
};

export default ChallengesAndConcernsPage;